[package]
name = "test-rustqlite"
version = "0.1.1"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]

[dependencies]
sqlite-wasm-uuid-rs = { path = "../" }
rusqlite = "0.38.0"
uuid = { version = "1.20.0" }
wasm-bindgen-test = "0.3.54"
